/** 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
 *
 * Ans = 4613732 
 */

public class Prob_2 {
	public static void main(String args[]) {
		int maxFibboNum = 4_000_000;
		int first = 1, second = 2, num, sum = 0;
		// first not added becoz it's not even num.
		sum += second;
		for(int i=3;i<=100;i++) {
			num = first + second;
			System.out.println("At:" + i +", " + num);
			if(num > maxFibboNum) {
				System.out.println(i+ ", " + num + " exceeded four milliion");
				break;
			}
			if(num % 2 == 0) {
				sum += num;
			}
			first = second;
			second = num;
		}
		System.out.println(sum);	
	}
}
